// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALc5PVpZREhlwyJqDcYK4WoObJd0qVBEk',
    appId: '1:225863527931:android:2e74af2473221f49802f5e',
    messagingSenderId: '225863527931',
    projectId: 'espitalia-eb27a',
    storageBucket: 'espitalia-eb27a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-7FmkHHum3uG8sKMwrXEgxtA76BvR3xc',
    appId: '1:225863527931:ios:21fb6dc348163d31802f5e',
    messagingSenderId: '225863527931',
    projectId: 'espitalia-eb27a',
    storageBucket: 'espitalia-eb27a.firebasestorage.app',
    iosClientId: '225863527931-3fctgvin4faehpme15l6hakdfds2lc90.apps.googleusercontent.com',
    iosBundleId: 'com.wellness.customer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFTPXrG-rNgIkjsQsOhZa_qp-Z_wf8qcs',
    appId: '1:225863527931:web:d889194e693a8a29802f5e',
    messagingSenderId: '225863527931',
    projectId: 'espitalia-eb27a',
    authDomain: 'espitalia-eb27a.firebaseapp.com',
    storageBucket: 'espitalia-eb27a.firebasestorage.app',
    measurementId: 'G-HD6LB2TYGM',
  );

}