// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    appId: "1:470329686255:android:22275b1bda3542326f031a", // mobilesdk_app_id
    apiKey: "AIzaSyDRO8UvG0R8NM7sfwl4c3ce7B78FMsQIF4",      // current_key
    projectId: "espitalia-d934b",                           // project_id
    messagingSenderId: "470329686255",                      // project_number
    storageBucket: "espitalia-d934b.firebasestorage.app",   // storage_bucket
  );
static const FirebaseOptions ios = FirebaseOptions(
  appId: "FIREBASE iOS APP ID",
  apiKey: 'FIREBASE API KEY',
  projectId: 'FIREBASE PROJECT ID',
  messagingSenderId: 'FIREBASE SENDER ID',
  storageBucket: 'FIREBASE STORAGE BUCKET',
  iosBundleId: 'FIREBASE iOS',
);

}
